on:
  workflow_call:
    inputs:
      directory:
        required: false
        type: string
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - uses: actions/setup-node@v3
        with:
          node-version: "16"
      - name: build smart contract
        if: ${{ inputs.directory }} != ''
        working-directory: ${{ inputs.directory }}
        run: |
          npm install
          npx hardhat compile
          npx hardhat test
      - name: build smart contract
        if: ${{ inputs.directory }} == ''
        run: |
          npm install
          npx hardhat compile
          npx hardhat test
