on:
  workflow_call:
    inputs:
      directory:
        required: false
        type: string
      file:
        required: false
        type: string
    secrets:
      alchemy_url:
        required: false
      etherscan_apikey:
        required: false
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - uses: actions/setup-node@v3
        with:
          node-version: "16"
      - name: run node file
        run: |
          cd ${{ inputs.directory }}
          npm install
          node ${{ inputs.file }}
